version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dartempire74/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    build: dartempire74/frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    build: dartempire74/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
